### ISSUE TITLE
EN 15804+A2 chapter 7.3.3.1 Modules B1-B5 use stage

### ISSUE THREAD

**Issue by RobertSpang** [InDataWG/ILCD-EPD-Data-Format#13]
### I raise this change request because...

- [ ] the ILCD+EPD format lacks compliance with regualtions.
- [X] the ILCD+EPD format lacks conformaty with standards.
- [ ] the ILCD+EPD format needs to be improved regarding existing format or master data elements.
- [ ] there is another problem or use case I´m trying to address.

### Problem description

![EN 15804+A2 chapter 7 3 3 1 Modules B (part 1)](https://github.com/InDataWG/ILCD-EPD-Data-Format/assets/150464594/494f67ce-0c15-4c9e-85fb-c3ae089990eb)
![EN 15804+A2 chapter 7 3 3 1 Modules B (part 2)](https://github.com/InDataWG/ILCD-EPD-Data-Format/assets/150464594/459bb94a-b519-4ebb-abf6-d4463767980f)

### Solution description

New master datasets need to be created and possibly the format extended

### Relevance or added value

Meduim relevance

**Comment by RobertSpang** [comment]
For Module B2, water and eneergy consuption should be 2 new fields.
Then we need new free text  fields for module B2, B3, B4, B5, since we don´t believe that we can make them machine readable for now. In addition, these fields are at the moment very rarely used because of the high dependency to the building context.

**Comment by okworx** [comment]
To be specified under "Technology description including background system" as free text.
