### ISSUE TITLE
EN 15804+A2 chapter 7.3.3.3 Modules B6-B7

### ISSUE THREAD

**Issue by RobertSpang** [InDataWG/ILCD-EPD-Data-Format#15]
### I raise this change request because...

- [ ] the ILCD+EPD format lacks compliance with regualtions.
- [x] the ILCD+EPD format lacks conformaty with standards.
- [ ] the ILCD+EPD format needs to be improved regarding existing format or master data elements.
- [ ] there is another problem or use case I´m trying to address.

### Problem description

![EN 15804+A2 chapter 7 3 3 3_Modules B6 and 7](https://github.com/InDataWG/ILCD-EPD-Data-Format/assets/150464594/99ac6738-857d-4997-bce4-786e3721ef82)

### Solution description

New master datasets need to be created and possibly the format extended

### Relevance or added value

Medium relevance

**Comment by RobertSpang** [comment]
We see redundancy with "Net use of fresh water" indicator of table 6.
For everything else we believe existing SI -units from our Master datasets should be sufficient.
Most interested seems to be the characteristic performace variables, since these allow for building specific calculations.
We assume we need to have new fields in the format to cover modules B6-B7 but we don´t need new Master Data.

**Comment by okworx** [comment]
To be specified under "Technology description including background system" as free text.
