### ISSUE TITLE
ISO 22057; production site(s) in GML according to ISO 19136-1

### ISSUE THREAD

**Issue by RobertSpang** [InDataWG/ILCD-EPD-Data-Format#23]
### I raise this change request because...

- [ ] the ILCD+EPD format lacks compliance with regualtions.
- [X] the ILCD+EPD format lacks conformaty with standards.
- [ ] the ILCD+EPD format needs to be improved regarding existing format or master data elements.
- [ ] there is another problem or use case I´m trying to address.

### Problem description

production site(s) in GML according to ISO 19136-1 is referred
also plus code(s) according to Open Location Code (OLC) are mentioned
Is connected to issue #22 

### Solution description

ISO 19136-1 & also plus code(s) according to Open Location Code (OLC) are mentioned needs to be checked, connection to issue #22 needs to be considered. Also connected to Martin Erlandsons request for geographical codes

### Relevance or added value

medium to high

**Comment by okworx** [comment]
addressed by #20
