### ISSUE TITLE
ISO 22057 - organisations authorised by the EPD owner(s) to use the EPD data

### ISSUE THREAD

**Issue by RobertSpang** [InDataWG/ILCD-EPD-Data-Format#26]
### I raise this change request because...

- [ ] the ILCD+EPD format lacks compliance with regualtions.
- [X] the ILCD+EPD format lacks conformaty with standards.
- [ ] the ILCD+EPD format needs to be improved regarding existing format or master data elements.
- [ ] there is another problem or use case I´m trying to address.

### Problem description

"organisations authorised by the EPD owner(s) to use the EPD data" shall be listed.

### Solution description

Don´t think that´s relevant, since EPDs are public documents?

### Relevance or added value

low

**Comment by okworx** [comment]
This is already covered by the existing field "Access and use restrictions".
