### ISSUE TITLE
ISO 22057 - biogenic carbon content

### ISSUE THREAD

**Issue by RobertSpang** [InDataWG/ILCD-EPD-Data-Format#28]
### I raise this change request because...

- [ ] the ILCD+EPD format lacks compliance with regualtions.
- [X] the ILCD+EPD format lacks conformaty with standards.
- [ ] the ILCD+EPD format needs to be improved regarding existing format or master data elements.
- [ ] there is another problem or use case I´m trying to address.

### Problem description

Refers to "biogenic carbon content packaging according to ISO 21930" & "biogenic carbon content within bio-based products according to ISO 21930"
Given unit is strange "kg CO₂ eq(100 years)" --> that´s not a carbon content but a CO2 equiv.
Already covered by current format by "flow properties" but with different unit

### Solution description

Further discussion needed

### Relevance or added value

low, since already part of "flow property"

**Comment by RobertSpang** [comment]
Since the unit is defined as CO2e. we suggest to implement that in the result table section.

**Comment by okworx** [comment]
I doubt that there are multiple different values for biogenic carbon content, and would assume that this is referring to the same biogenic carbon content that is mandated by EN15804+A2, which is already modelled by means of dedicated flow properties (for product and packaging).
