### ISSUE TITLE
ISO 22057 - Reference unit and RSL - factors and factor categories according to ISO 15686-8

### ISSUE THREAD

**Issue by RobertSpang** [InDataWG/ILCD-EPD-Data-Format#30]
### I raise this change request because...

- [ ] the ILCD+EPD format lacks compliance with regualtions.
- [X] the ILCD+EPD format lacks conformaty with standards.
- [ ] the ILCD+EPD format needs to be improved regarding existing format or master data elements.
- [ ] there is another problem or use case I´m trying to address.

### Problem description

"factors and categories of in-use conditions that are considered in the determination of an ESL from an RSL" --> A-inherent performance level; B-design level; C-work execution level; D-indoor environment; E-outdoor environment; F-usage conditions; G-maintenance level

&

"designation representing a qualitative description of the in-use condition grading" --> 0; 1; 2; 3; 4; 5; NA

### Solution description

Further research needed; relevance should be checked. Could maybe be postponed for now.

### Relevance or added value

Today of minor importance since ISO 15686-8 is not widely used.

**Comment by RobertSpang** [comment]
We should get an example of the actual use of ESL and RSL to get a better understanding of the use-case. In the end it should be meaningful/useful information for the building level. Robert will request Ecoplatform to raise the question to their members if anyone used ESL/RSL acc ISO 15686-8 in an EPD.

**Comment by okworx** [comment]
see https://github.com/InDataWG/ILCD-EPD-Data-Format/issues/14
